version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package

artifacts:
  files:
    - target/game-backend-1.0-SNAPSHOT-jar-with-dependencies.jar
    - appspec.yml
    - scripts/run_app.sh
    - scripts/stop_app.sh
    - scripts/pm2process.sh
    - scripts/install_dependencies.sh
  discard-paths: yes